server:
  servlet:
    context-path: /api/ai-resume-builder-service

spring:
  application:
    name: ai-resume-builder-service
  ai:
    ollama:
      chat:
        model: "deepseek-r1:latest"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    root: INFO
    in.oceanbytes.ai_resume_builder_service: INFO